### PR TITLE
Add type annotation support and mapping info in jd gen

### LINKED ISSUE #3: Type annotations
Minecraft is compiled against Java 8, which introduced [type annotations](https://docs.oracle.com/javase/specs/jvms/se14/html/jvms-4.html#jvms-4.7.20).

It does not appear that Minecraft makes extensive use of them, so currently this is not of high priority.

A trouble with type annotations in implementation is that these annotations are specified by locations and paths, which are harder to index compared to regular annotations or signatures (given how javapoet builds source model with type annotations). Might need to pass a type annotation context to the whole signature/descriptor parsing utilities.

### LINKED ISSUE #5: Auto include intermediary/obfuscated name info in javadoc
I propose doing this with 2 custom taglets, one for classes and the other one for the name+desc of methods/fields. We will have a simple taglet that takes the obfuscation info and produce some html snippet that creates a nice embed for the intermediary/official names of a member.

### PR DESCRIPTION
**Pull request by liach**
Closes #3 and closes #5
Now requires Java 11 as I wrote the taglet for java 9's taglet api

Generated source code from 20w51a:
[20w51atest.zip](https://github.com/FabricMC/MappingPoet/files/5736154/20w51atest.zip)

Selected generated javadoc from code above (excluded some dir as otherwise the archive would be too large):
[test51adoc.zip](https://github.com/FabricMC/MappingPoet/files/5736176/test51adoc.zip)

Example pic:
image

### CODE REVIEW

**Review by modmuss50 — APPROVED** [review]
Awesome work 👍 

Not really feasible for me to do an indepth review due to the size and complexity and I dont think it would be of much help.

As for the Java 11 requirement to use this in yarn there are 2 options:

- Make yarn require java 11 (seem resonable, im gaining feedback on this)
- Use gradle's toolchain feature to download java 11 to run this.

**Comment by liach** [comment]
Looking at FabricMC/Enigma#321, we might just do the same but go straight to Java 15. However, since the [`Main` is called directly by the buildscript](https://github.com/FabricMC/yarn/blob/6bd581026ea382b0419fbeceade265ba803acbd4/build.gradle#L672), I think gradle itself should run on newer java unless we change that task to a standalone `JavaExec`.

**Comment by liach** [comment]
I will merge this one for now. Since yarn depends on hardcoded 0.1.0+build.2, if the build fails, it should not hurt yarn. This build should pass; I can then test on yarn.

**Comment by liach** [comment]
Hmm, seems Jenkins is not building at https://jenkins.modmuss50.me/job/FabricMC/job/MappingPoet/job/master/
might need some help.

**Comment by modmuss50** [comment]
Jenkins is no longer used. I’ll move it over to GitHub actions and make a release. 👍

**Comment by modmuss50** [comment]
Done, you can find it here: https://maven.fabricmc.net/net/fabricmc/mappingpoet/0.2.0/

**Comment by i509VCB** [comment]
Mixin form should probably be more appropriately named `Mixin selector`

**Comment by liach** [comment]
> 
> 
> Mixin form should probably be more appropriately named `Mixin selector`

Feel free to patch it here https://github.com/FabricMC/MappingPoet/blob/9abf2a8efe35fcad9f54469a1916ff6b96509ecb/src/main/java/net/fabricmc/mappingpoet/jd/MappingTaglet.java#L73 and submit a pr :laughing:

**Pull request merged**
